### ISSUE TITLE
Question about ‘z' interpolation

### ISSUE THREAD

**Issue by byh299792458** [trenki2/SoftwareRenderer#1]
Thank you for your code，I have learned a lot from it. But I have a question about z-coordinate interpolation：
       In my opinion, z-coordinate is a perspective variable but not a affine variable. So I think you should interpolate z/w first，and then recover z-coordinate from  z'/w'.  Before deviding by w，z-coordinate is linear with x-coordinate and y-coordinate. But during rasterizer，z is not linear with them.
        So is it right？

**Comment by trenki2** [comment]
The first version of my rasterizer only did affine interpolation of all the variables including z. In the pixel shader you would use the z coordinate most likely for a z-buffer test. In this case it does not make much difference if it is linearly interpolated or perspectively correct.

Later I added the possibility to interpolate vertex attributes perspectively correct. I left the interpolation of the z coordinate as is, so that you do not pay the cost of interpolating 1/w if you don't want to use perspectively correct variables.

I guess you could interpolate it in a perspectively correct way, but I think for all practical purposes it does not make much difference.

While going over the code I found some small issues. Just make a git pull and you will get the newest code.
